### ISSUE TITLE
Newest versions of gamescope flatpak no longer works due to X server error.

### ISSUE THREAD

**Issue by LostWarriorr** [flathub/org.freedesktop.Platform.VulkanLayer.gamescope#122]
Using the gamescope %command% in steam flatpak (and potentially other flatpaks) no longer work with the 2 latest versions(?) of gamescope flatpak. Black Window will open and immediately close with the following error:

`(EE) failed to read Wayland events: Connection reset by peer`
`XIO:  fatal IO error 2 (No such file or directory) on X server ":2"`
`after 780 requests (780 known processed) with 22 events remaining.`
      
Reverting back to this version of gamescope flatpak solves this issue:

`flatpak update --commit=0b3543a920d07271426945f9ebde207de89232475d6f6ba8bf98ff7cb3f2590e runtime/org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/23.08`

Latest version of packages used that were available on said Distro.

Distro: Debian sid

DE: KDE Plasma using wayland (and X11)

GPU: AMD 6800xt

CPU: 5800x3D

Monitors: 1080p 144hz and 1080p 60hz

Pipewire is being used and not pulseaudio if that is another factor

**Comment by Equivocal90** [comment]
I have the same issue.

While the latest version failed for Steam and some other apps, ~~it did work in at least one scenario for me. I use gamescope with XIVLauncher by overriding the desktop file with roughly `flatpak run --command=/usr/lib/extensions/vulkan/gamescope/bin/gamescope dev.goats.xivlauncher -- xivlauncher`~~


Distro: Fedora Silverblue 39
DE: GNOME Wayland
GPU: AMD 6700 XT 
CPU: 7840U
Monitor: 4K 60hz in use and a 1600P 60hz that is off.

Edit: I realize now that it worked with XIVLauncher because it is still on the 22.08 runtime.

**Comment by ColinKinloch** [comment]
Does the build at https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/pull/91 work:
```
flatpak install --user https://dl.flathub.org/build-repo/71128/org.freedesktop.Platform.VulkanLayer.gamescope.flatpakref
```

**Comment by Zalaxx** [comment]
It works like a charm!
I tried it with Genshin Impact via An Anime Game Launcher, Cyberpunk 2077 from Steam Flatpak (with GE-Proton8-24), and Oxygen Not Included also from Steam Flatpak (Linux native).

**Comment by Equivocal90** [comment]
That worked for me also.

**Comment by ColinKinloch** [comment]
Good to hear!
Hopefully @orowith2os will find time to review the changes soon.

**Comment by zastrixarundell** [comment]
Build from #91 didn't work for me on steam flatpak and GE-24. I get the following error:

```
CreateSwapchainKHR: Creating swapchain for non-Gamescope swapchain.
Hooking has failed somewhere!
You may have a bad Vulkan layer interfering.
Press OK to try to power through this error, or Cancel to stop.
```

![image](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/assets/30195425/47269634-d2bd-49e5-b614-773f2789e690)

Command was: `gamescope -h 720 -H 1080 -f -- %command%`

**Comment by Zalaxx** [comment]
Yea I also have this issue with Cyberpunk 2077, but it was also happening with the specific version of gamescope from the original issue (commit 0b3543a920d07271426945f9ebde207de89232475d6f6ba8bf98ff7cb3f2590e). I just press OK two times (the popup reappears once) and the game runs fine. I don't have this issue with other games though.

Can you confirm the error was not happening before, and that it completely prevents you from running the game?

System Infos: 
OS: Fedora Silverblue 39
Kernel: 6.6.6
DE: GNOME 45.2 (Wayland)
GPU: AMD Radeon RX 6600M
CPU: AMD Ryzen 5 5600H

**Comment by zastrixarundell** [comment]
Yeah it's happening on both version of gamescope but on every game. Also running Fedora Kinoite Ublue latest.

```bash
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 8h ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:latest
                   Digest: sha256:d0bc212d46c134da97da130b50965f33f2880cc43fa4793df8e5b9c5118aea70
                  Version: 39.20231215.0 (2023-12-15T15:06:29Z)
      RemovedBasePackages: firefox firefox-langpacks 120.0.1-1.fc39
          LayeredPackages: code corectrl gnome-boxes goverlay pulseaudio-utils v4l2loopback valgrind virt-manager
                           WoeUSB zsh
```
```bash
$ uname -nr
main-pc 6.6.6-200.fc39.x86_64
```

KDE running Wayland on AMD 6600XT and a i7 9700k.

Pressing OK will start the game but at least what I see on Elder Scrolls Online it ignores gamescope config for resolution, allowing me to set the game to 1080p even though I set the game view to 720p on gamescope.

It at least *runs* the game now but there's an issue that from my POV gamescope doesn't work fully.

Edit:

I ran with the `-r 30` option under steam flatpak and it didn't limit doom eternal to 30fps. 

Edit v2:

I can't run this version of gamescope at all due to this error everywhere when I use heroic launcher or the flatpak version of proton on steam:
![image](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/assets/30195425/2af6f11d-ce90-4c47-9073-62bc844a36d3)

**Comment by eskay993** [comment]
Thanks for this! Just to report version `3.13.19` released today has fixed the issue for me. I was having the same issue as OP with similar specs (except I'm on Garuda) and same error message, Now gamescope is working again in Lutris flatpak.

Not tested Steam flatpak as  I don't use it.

**Comment by LostWarriorr** [comment]
My original issue has been solved but there has definitely been discussion of a bunch of other issues. 

I get the one mentioned in [this comment](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/issues/122#issuecomment-1862501139) and gamescope is not correctly started (Risk of rain 2 before some gamescope update) (Playable)
Along with these two
 `Switching to resolution 1920x1080 failed`
`Screen: DX11 could not switch resolution (1920x1080 fs=1 hz=0)` (Risk of rain 2 current gamescope version) (crashes)

`Win32 function failed: HRESULT: 0x80004005`
`Call: pDXGIFactory->CreateSwapChain at line 503 in file \Graphics_DisplayM.cpp` (Risk of rain returns current gamescope version) (crashes)

EDIT: These do not happen on native steam/gamescope
